INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jose Ferrer', 'SEA', 'RP', 'Claim', 'Crazyhorse (T)', 1, '2026-05-10 10:00:00', 47);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Javier Sanoja', 'MIA', '2B,3B,OF,P', 'Drop', 'Crazyhorse (T)', NULL, '2026-05-10 10:00:00', 47);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jake McCarthy', 'COL', 'OF', 'Claim', 'Master Chief (T)', 0, '2026-05-09 10:00:00', 46);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Zack Gelof', 'ATH', '2B,OF', 'Claim', 'Master Chief (T)', 1.5, '2026-05-09 10:00:00', 46);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ty Madden', 'DET', 'SP', 'Claim', 'DirkDiggler (T)', 2, '2026-05-09 10:00:00', 46);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Orion Kerkering', 'PHI', 'RP', 'Drop', 'DirkDiggler (T)', NULL, '2026-05-09 10:00:00', 46);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jose Fernandez', 'ARI', '1B,SS', 'Drop', 'Crazyhorse (T)', NULL, '2026-05-08 16:46:00', 45);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Christian Vazquez', 'HOU', 'C', 'Claim', 'Duke Nukem (T)', 10, '2026-05-08 10:00:00', 45);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ezequiel Duran', 'TEX', '1B,2B,SS,OF', 'Claim', 'Rick Grimes (T)', 0, '2026-05-08 10:00:00', 45);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jorge Mateo', 'ATL', 'SS', 'Drop', 'Rick Grimes (T)', NULL, '2026-05-08 10:00:00', 45);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Curtis Mead', 'WSH', '1B,3B', 'Claim', 'DirkDiggler (T)', 0, '2026-05-08 10:00:00', 45);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler Freeman', 'COL', 'OF', 'Drop', 'DirkDiggler (T)', NULL, '2026-05-08 10:00:00', 45);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Pedro Ramirez', 'CHC', '2B,3B,SS', 'Claim', 'Master Chief (T)', 0, '2026-05-06 10:00:00', 43);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jhostynxon Garcia', 'PIT', 'OF', 'Drop', 'Master Chief (T)', NULL, '2026-05-06 10:00:00', 43);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nathaniel Lowe', 'CIN', '1B', 'Claim', 'Master Chief (T)', 1.5, '2026-05-06 10:00:00', 43);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('JJ Bleday', 'CIN', 'OF', 'Claim', 'Crazyhorse (T)', 0, '2026-05-06 10:00:00', 43);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Matt Waldron', 'SD', 'SP', 'Claim', 'Haru''s Throwing Stars (T)', 0, '2026-05-06 10:00:00', 43);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Patrick Corbin', 'TOR', 'SP', 'Claim', 'XENOMORPH (T)', 0.5, '2026-05-06 10:00:00', 43);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Luisangel Acuna', 'CHW', '2B,SS,OF', 'Drop', 'XENOMORPH (T)', NULL, '2026-05-06 10:00:00', 43);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Braylon Doughty', 'CLE', 'SP', 'Drop', 'Crazyhorse (T)', NULL, '2026-05-06 07:58:00', 43);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Anthony Nunez', 'BAL', 'RP', 'Drop', 'Master Chief (T)', NULL, '2026-05-06 06:06:00', 43);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Keider Montero', 'DET', 'SP', 'Claim', 'Crazyhorse (T)', 3, '2026-05-05 10:00:00', 42);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Luis Campusano', 'SD', 'C', 'Claim', 'XENOMORPH (T)', 0, '2026-05-05 10:00:00', 42);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Austin Hays', 'CHW', 'OF', 'Drop', 'XENOMORPH (T)', NULL, '2026-05-05 10:00:00', 42);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kohl Drake', 'ARI', 'SP', 'Drop', 'Crazyhorse (T)', NULL, '2026-05-04 11:11:00', 41);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tristan Peters', 'CHW', 'OF', 'Claim', 'Crazyhorse (T)', 0, '2026-05-04 10:00:00', 41);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Griffin Conine', 'MIA', 'OF', 'Drop', 'Crazyhorse (T)', NULL, '2026-05-04 10:00:00', 41);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Janson Junk', 'MIA', 'SP', 'Claim', 'XENOMORPH (T)', 1, '2026-05-04 10:00:00', 41);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Justin Sterner', 'ATH', 'RP', 'Drop', 'XENOMORPH (T)', NULL, '2026-05-04 10:00:00', 41);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jose Berrios', 'TOR', 'SP', 'Claim', 'Star Lord (T)', 1, '2026-05-03 10:00:00', 40);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kyle Finnegan', 'DET', 'RP', 'Claim', 'Crazyhorse (T)', 0, '2026-05-03 10:00:00', 40);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Matt Svanson', 'STL', 'RP', 'Drop', 'Crazyhorse (T)', NULL, '2026-05-03 10:00:00', 40);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Yohan Ramirez', 'PIT', 'RP', 'Claim', 'Star Lord (T)', 1, '2026-05-03 10:00:00', 40);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Michael Lorenzen', 'COL', 'SP', 'Drop', 'Star Lord (T)', NULL, '2026-05-03 10:00:00', 40);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Dane Myers', 'CIN', 'OF', 'Drop', 'Master Chief (T)', NULL, '2026-05-02 22:30:00', 40);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Felipe De La Cruz', 'NYM', 'RP', 'Drop', 'Star Lord (T)', NULL, '2026-05-02 10:58:00', 39);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Dane Myers', 'CIN', 'OF', 'Claim', 'Master Chief (T)', 0, '2026-05-02 10:00:00', 39);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('J.T. Ginn', 'ATH', 'SP', 'Claim', 'Master Chief (T)', 0, '2026-05-01 10:00:00', 38);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Colin Rea', 'CHC', 'SP', 'Claim', 'Master Chief (T)', 1, '2026-05-01 10:00:00', 38);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brandon Young', 'BAL', 'SP', 'Drop', 'Master Chief (T)', NULL, '2026-05-01 10:00:00', 38);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Eric Hartman', 'ATL', '2B,OF', 'Claim', 'Master Chief (T)', 0, '2026-05-01 10:00:00', 38);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Casey Schmitt', 'SF', '1B,2B,3B', 'Claim', 'Crazyhorse (T)', 0, '2026-05-01 10:00:00', 38);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Carson Whisenhunt', 'SF', 'SP', 'Drop', 'Crazyhorse (T)', NULL, '2026-05-01 10:00:00', 38);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Daniel Lynch', 'KC', 'RP', 'Claim', 'Riddle me This" (T)"', 0, NULL, 37);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jameson Taillon', 'CHC', 'SP', 'Claim', 'Crazyhorse (T)', 4, NULL, 37);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brandon Williamson', 'CIN', 'SP', 'Drop', 'Crazyhorse (T)', NULL, NULL, 37);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Robert Garcia', 'TEX', 'RP', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 36);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Keaton Winn', 'SF', 'RP', 'Claim', 'Crazyhorse (T)', 0, NULL, 35);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jordan Romano', 'COL', 'RP', 'Drop', 'Crazyhorse (T)', NULL, NULL, 35);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Erik Miller', 'SF', 'RP', 'Claim', 'Star Lord (T)', 1, NULL, 34);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Adrian Houser', 'SF', 'SP', 'Drop', 'Star Lord (T)', NULL, NULL, 34);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jacob Lopez', 'ATH', 'SP', 'Drop', 'Master Chief (T)', NULL, NULL, 34);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Mike Yastrzemski', 'ATL', 'OF', 'Drop', 'Master Chief (T)', NULL, NULL, 34);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Daniel Schneemann', 'CLE', '2B,3B,OF', 'Claim', 'The Prime Evils (T)', 1, NULL, 33);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ryan Lambert', 'NYM', 'RP', 'Drop', 'The Prime Evils (T)', NULL, NULL, 33);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Felix Bautista', 'BAL', 'RP', 'Drop', 'Master Chief (T)', NULL, NULL, 33);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Zack Littell', 'WSH', 'SP', 'Drop', 'Master Chief (T)', NULL, NULL, 33);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Braylon Payne', 'MIL', 'OF', 'Claim', 'Master Chief (T)', 0, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Santiago Suarez', 'TB', 'SP', 'Drop', 'Master Chief (T)', NULL, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Khal Stephen', 'CLE', 'SP', 'Claim', 'Master Chief (T)', 0, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kemp Alderman', 'MIA', 'OF', 'Drop', 'Master Chief (T)', NULL, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Isaac Mattson', 'PIT', 'RP', 'Claim', 'Crazyhorse (T)', 0, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Caleb Thielbar', 'CHC', 'RP', 'Drop', 'Crazyhorse (T)', NULL, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Peter Lambert', 'HOU', 'SP', 'Claim', 'XENOMORPH (T)', 4, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Denzel Clarke', 'ATH', 'OF', 'Drop', 'XENOMORPH (T)', NULL, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Dylan Lee', 'ATL', 'RP', 'Claim', 'DirkDiggler (T)', 1, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jameson Taillon', 'CHC', 'SP', 'Drop', 'DirkDiggler (T)', NULL, NULL, 32);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Lucas Giolito', 'SD', 'SP', 'Claim', 'Crazyhorse (T)', 5, NULL, 31);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ethan Pecko', 'HOU', 'SP', 'Drop', 'Crazyhorse (T)', NULL, NULL, 31);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brandon Young', 'BAL', 'SP', 'Claim', 'Master Chief (T)', 1, NULL, 31);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Andruw Monasterio', 'BOS', 'SS', 'Drop', 'Rick Grimes (T)', NULL, NULL, 31);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ronel Blanco', 'HOU', 'SP', 'Drop', 'Rick Grimes (T)', NULL, NULL, 31);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ronny Cruz', 'WSH', 'SS', 'Claim', 'Master Chief (T)', 0, NULL, 30);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Caleb Thielbar', 'CHC', 'RP', 'Claim', 'Crazyhorse (T)', 0, NULL, 30);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Khal Stephen', 'CLE', 'SP', 'Drop', 'Crazyhorse (T)', NULL, NULL, 30);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Gus Varland', 'WSH', 'RP', 'Claim', 'Rick Grimes (T)', 0, NULL, 30);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler Alexander', 'TEX', 'RP', 'Claim', 'DirkDiggler (T)', 0, NULL, 30);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Drew Millas', 'WSH', 'C', 'Drop', 'Rick Grimes (T)', NULL, NULL, 30);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nick Fortes', 'TB', 'C', 'Drop', 'DirkDiggler (T)', NULL, NULL, 29);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Mike Yastrzemski', 'ATL', 'OF', 'Claim', 'Master Chief (T)', 0, NULL, 28);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Anthony Eyanson', 'BOS', 'SP', 'Claim', 'Master Chief (T)', 0, NULL, 28);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Luis Lara', 'MIL', 'OF', 'Claim', 'Master Chief (T)', 0, NULL, 28);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Bradgley Rodriguez', 'SD', 'RP', 'Claim', 'Master Chief (T)', 0, NULL, 27);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Aaron Civale', 'ATH', 'SP', 'Drop', 'Master Chief (T)', NULL, NULL, 27);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Camilo Doval', 'NYY', 'RP', 'Drop', 'Master Chief (T)', NULL, NULL, 27);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler Phillips', 'MIA', 'RP', 'Claim', 'Rick Grimes (T)', 0, NULL, 26);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Grant Wolfram', 'BAL', 'RP', 'Claim', 'Master Chief (T)', 0.25, NULL, 26);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Shawn Armstrong', 'CLE', 'RP', 'Drop', 'Master Chief (T)', NULL, NULL, 26);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ildemaro Vargas', 'ARI', '1B,2B', 'Claim', 'Rick Grimes (T)', 0, NULL, 26);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Max Scherzer', 'TOR', 'SP', 'Drop', 'Rick Grimes (T)', NULL, NULL, 26);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nate Eaton', 'BOS', 'OF', 'Drop', 'Rick Grimes (T)', NULL, NULL, 26);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Leody Taveras', 'BAL', 'OF', 'Claim', 'Crazyhorse (T)', 0, NULL, 25);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brandon Lockridge', 'MIL', 'OF', 'Drop', 'Crazyhorse (T)', NULL, NULL, 25);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Joel Kuhnel', 'ATH', 'RP', 'Claim', 'XENOMORPH (T)', 1.5, NULL, 25);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Luis Morales', 'ATH', 'SP', 'Drop', 'XENOMORPH (T)', NULL, NULL, 25);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jeremiah Jackson', 'BAL', '2B,OF', 'Claim', 'Haru''s Throwing Stars (T)', 0, NULL, 25);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Simeon Woods-Richardson', 'MIN', 'SP', 'Drop', 'Haru''s Throwing Stars (T)', NULL, NULL, 25);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Mason Montgomery', 'PIT', 'RP', 'Claim', 'DirkDiggler (T)', 0, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Andrew Morris', 'MIN', 'SP', 'Drop', 'DirkDiggler (T)', NULL, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Carson Kelly', 'CHC', 'C', 'Claim', 'DirkDiggler (T)', 0, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Alek Thomas', 'ARI', 'OF', 'Drop', 'DirkDiggler (T)', NULL, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Oswald Peraza', 'LAA', '2B,3B', 'Claim', 'Master Chief (T)', 0, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Mike Yastrzemski', 'ATL', 'OF', 'Drop', 'Master Chief (T)', NULL, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Gary Sanchez', 'MIL', 'C', 'Claim', 'Master Chief (T)', 0, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Luke Weaver', 'NYM', 'RP', 'Drop', 'Master Chief (T)', NULL, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Carlos Cortes', 'ATH', 'OF', 'Claim', 'Crazyhorse (T)', 0, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jake McCarthy', 'COL', 'OF', 'Drop', 'Crazyhorse (T)', NULL, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Bryan Baker', 'TB', 'RP', 'Claim', 'DirkDiggler (T)', 1, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jose Ferrer', 'SEA', 'RP', 'Drop', 'DirkDiggler (T)', NULL, NULL, 24);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Austin Martin', 'MIN', 'OF', 'Claim', 'Minneapolis Millers (T)', 2, NULL, 23);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler O''Neill', 'BAL', 'OF', 'Drop', 'Minneapolis Millers (T)', NULL, NULL, 23);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Lake Bachar', 'MIA', 'RP', 'Claim', 'Riddle me This" (T)"', 0, NULL, 22);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kai-Wei Teng', 'HOU', 'SP', 'Claim', 'Rick Grimes (T)', 0, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jorge Mateo', 'ATL', 'SS', 'Claim', 'Rick Grimes (T)', 0, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brandon Marsh', 'PHI', 'OF', 'Claim', 'Crazyhorse (T)', 1, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nathan Lukes', 'TOR', 'OF', 'Drop', 'Crazyhorse (T)', NULL, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Edouard Julien', 'COL', '1B,2B', 'Claim', 'Crazyhorse (T)', 1, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Oswald Peraza', 'LAA', '2B,3B', 'Drop', 'Crazyhorse (T)', NULL, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jack Kochanowicz', 'LAA', 'SP', 'Claim', 'Rick Grimes (T)', 0.25, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Andrew Morris', 'MIN', 'SP', 'Claim', 'DirkDiggler (T)', 0, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Cade Povich', 'BAL', 'SP', 'Drop', 'DirkDiggler (T)', NULL, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kyle Freeland', 'COL', 'SP', 'Drop', 'Master Chief (T)', NULL, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tanner Houck', 'BOS', 'SP', 'Drop', 'Rick Grimes (T)', NULL, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tanner Houck', 'BOS', 'SP', 'Drop', 'Rick Grimes (T)', NULL, NULL, 21);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brusdar Graterol', 'LAD', 'RP', 'Drop', 'Rick Grimes (T)', NULL, NULL, 20);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jameson Taillon', 'CHC', 'SP', 'Claim', 'DirkDiggler (T)', 1, NULL, 20);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nick Fortes', 'TB', 'C', 'Claim', 'DirkDiggler (T)', 1, NULL, 20);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Louis Varland', 'TOR', 'RP', 'Claim', 'DirkDiggler (T)', 1, NULL, 20);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jorge Soler', 'LAA', 'OF', 'Claim', 'Haru''s Throwing Stars (T)', 18, NULL, 20);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Cade Povich', 'BAL', 'SP', 'Claim', 'DirkDiggler (T)', 1, NULL, 20);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kyle Finnegan', 'DET', 'RP', 'Drop', 'DirkDiggler (T)', NULL, NULL, 20);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Cristian Javier', 'HOU', 'SP', 'Drop', 'DirkDiggler (T)', NULL, NULL, 20);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Andrew Kittredge', 'BAL', 'RP', 'Drop', 'DirkDiggler (T)', NULL, NULL, 20);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Antonio Senzatela', 'COL', 'SP', 'Claim', 'XENOMORPH (T)', 0.5, NULL, 19);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jared Koenig', 'MIL', 'RP', 'Drop', 'XENOMORPH (T)', NULL, NULL, 19);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Anthony Nunez', 'BAL', 'RP', 'Claim', 'Master Chief (T)', 0, NULL, 19);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Aaron Civale', 'ATH', 'SP', 'Claim', 'Master Chief (T)', 0, NULL, 19);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Juan Morillo', 'ARI', 'RP', 'Claim', 'XENOMORPH (T)', 0, NULL, 19);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brandon Lockridge', 'MIL', 'OF', 'Claim', 'Crazyhorse (T)', 1, NULL, 18);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jake Fraley', 'TB', 'OF', 'Drop', 'Crazyhorse (T)', NULL, NULL, 18);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Rico Garcia', 'BAL', 'RP', 'Claim', 'Star Lord (T)', 1, NULL, 18);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Dylan Lesko', 'TB', 'RP', 'Drop', 'Star Lord (T)', NULL, NULL, 18);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Keibert Ruiz', 'WSH', 'C', 'Drop', 'DirkDiggler (T)', NULL, NULL, 18);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Griffin Conine', 'MIA', 'OF', 'Claim', 'Crazyhorse (T)', 0.5, NULL, 16);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Daniel Susac', 'SF', 'C', 'Claim', 'Crazyhorse (T)', 0.5, NULL, 16);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tomoyuki Sugano', 'COL', 'SP', 'Claim', 'Star Lord (T)', 1, NULL, 16);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Harrison Bader', 'SF', 'OF', 'Drop', 'Star Lord (T)', NULL, NULL, 16);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Billy Carlson', 'CHW', 'SS', 'Drop', 'Crazyhorse (T)', NULL, NULL, 16);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Noble Meyer', 'MIA', 'SP', 'Drop', 'Crazyhorse (T)', NULL, NULL, 15);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kyle Freeland', 'COL', 'SP', 'Claim', 'Master Chief (T)', 0, NULL, 15);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Phil Maton', 'CHC', 'RP', 'Drop', 'Master Chief (T)', NULL, NULL, 15);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Javier Sanoja', 'MIA', '2B,3B,OF,P', 'Claim', 'Crazyhorse (T)', 2, NULL, 15);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brice Matthews', 'HOU', '2B,OF', 'Drop', 'Crazyhorse (T)', NULL, NULL, 15);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Max Scherzer', 'TOR', 'SP', 'Claim', 'Rick Grimes (T)', 0.25, NULL, 15);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Zach Eflin', 'BAL', 'SP', 'Drop', 'Rick Grimes (T)', NULL, NULL, 15);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jakob Junis', 'TEX', 'RP', 'Claim', 'Master Chief (T)', 1, NULL, 14);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Braydon Fisher', 'TOR', 'RP', 'Claim', 'Master Chief (T)', 0, NULL, 14);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Hunter Harvey', 'CHC', 'RP', 'Drop', 'Master Chief (T)', NULL, NULL, 14);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Cody Bolton', 'HOU', 'SP', 'Claim', 'Rick Grimes (T)', 2, NULL, 13);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Wikelman Gonzalez', 'CHW', 'RP', 'Drop', 'Rick Grimes (T)', NULL, NULL, 13);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Davis Martin', 'CHW', 'SP', 'Claim', 'Rick Grimes (T)', 2, NULL, 13);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Keibert Ruiz', 'WSH', 'C', 'Claim', 'DirkDiggler (T)', 1, NULL, 13);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('A.J. Blubaugh', 'HOU', 'RP', 'Drop', 'DirkDiggler (T)', NULL, NULL, 13);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Keaton Winn', 'SF', 'RP', 'Drop', 'Master Chief (T)', NULL, NULL, 12);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Anthony Kay', 'CHW', 'SP', 'Drop', 'Master Chief (T)', NULL, NULL, 12);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('A.J. Blubaugh', 'HOU', 'RP', 'Claim', 'DirkDiggler (T)', 1, NULL, 11);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jonathan Loaisiga', 'ARI', 'RP', 'Claim', 'San Diego Deathstroke (T)', 2, NULL, 10);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Dominic Smith', 'ATL', '1B', 'Claim', 'Master Chief (T)', 0, NULL, 10);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Connor Norby', 'MIA', '1B,3B', 'Drop', 'Master Chief (T)', NULL, NULL, 10);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nasim Nunez', 'WSH', '2B,SS', 'Claim', 'San Diego Deathstroke (T)', 4, NULL, 10);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kyle Isbel', 'KC', 'OF', 'Claim', 'Master Chief (T)', 0.25, NULL, 9);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Keaton Winn', 'SF', 'RP', 'Claim', 'Master Chief (T)', 0, NULL, 9);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nick Martinez', 'TB', 'SP', 'Claim', 'Star Lord (T)', 1, NULL, 9);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brendan Rodgers', 'BOS', '2B', 'Drop', 'Star Lord (T)', NULL, NULL, 9);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jose Fernandez', 'ARI', '1B,SS', 'Claim', 'Crazyhorse (T)', 2, NULL, 8);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Cooper Criswell', 'SEA', 'RP', 'Claim', 'Rick Grimes (T)', 2, NULL, 8);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jordan Romano', 'COL', 'RP', 'Claim', 'Crazyhorse (T)', 2, NULL, 8);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Oswald Peraza', 'LAA', '2B,3B', 'Claim', 'Crazyhorse (T)', 2, NULL, 8);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Graham Ashcraft', 'CIN', 'RP', 'Claim', 'Rick Grimes (T)', 2, NULL, 8);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Rob Refsnyder', 'SEA', 'OF,UT', 'Drop', 'Crazyhorse (T)', NULL, NULL, 8);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Cedric Mullins', 'TB', 'OF', 'Drop', 'DirkDiggler (T)', NULL, NULL, 8);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Mikey Romero', 'BOS', '2B,3B,SS', 'Drop', 'Crazyhorse (T)', NULL, NULL, 8);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Michael Soroka', 'ARI', 'SP', 'Claim', 'Minneapolis Millers (T)', 8, NULL, 7);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Yolfran Castillo', 'TEX', '3B,SS', 'Drop', 'Minneapolis Millers (T)', NULL, NULL, 7);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler O''Neill', 'BAL', 'OF', 'Claim', 'Minneapolis Millers (T)', 22, NULL, 7);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Pedro Pages', 'STL', 'C', 'Claim', 'Riddle me This" (T)"', 1, NULL, 6);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nick Gonzales', 'PIT', '2B,3B', 'Claim', 'Duke Nukem (T)', 4, NULL, 6);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Luke Raley', 'SEA', '1B,OF', 'Claim', 'Duke Nukem (T)', 3, NULL, 6);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Fernando Cruz', 'NYY', 'RP', 'Drop', 'Master Chief (T)', NULL, NULL, 6);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Andrew Benintendi', 'CHW', 'OF', 'Drop', 'Master Chief (T)', NULL, NULL, 6);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ryan Weiss', 'HOU', 'SP', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 6);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Esteury Ruiz', 'MIA', 'OF', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 6);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Trey Sweeney', 'DET', 'SS', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 6);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Joey Wiemer', 'WSH', 'OF', 'Claim', 'Iron Fisting (T)', 2, NULL, 5);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('David Hamilton', 'MIL', '2B,3B,SS', 'Claim', 'Iron Fisting (T)', 2, NULL, 5);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Anthony Kay', 'CHW', 'SP', 'Claim', 'Master Chief (T)', 0, NULL, 5);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ryan Ritter', 'COL', '2B,SS', 'Drop', 'Master Chief (T)', NULL, NULL, 5);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kyle Finnegan', 'DET', 'RP', 'Claim', 'DirkDiggler (T)', 1, NULL, 5);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Eric Orze', 'MIN', 'RP', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 5);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Erik Sabrowski', 'CLE', 'RP', 'Claim', 'Master Chief (T)', 4, NULL, 4);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jake Meyers', 'HOU', 'OF', 'Drop', 'Master Chief (T)', NULL, NULL, 4);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Rob Refsnyder', 'SEA', 'OF,UT', 'Claim', 'Crazyhorse (T)', 2, NULL, 4);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Carter Baumler', 'TEX', 'RP', 'Claim', 'Riddle me This" (T)"', 1, NULL, 4);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Emiliano Teodo', 'TEX', 'RP', 'Drop', 'Crazyhorse (T)', NULL, NULL, 4);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Christian Oppor', 'CHW', 'SP', 'Drop', 'Crazyhorse (T)', NULL, NULL, 4);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Louis Varland', 'TOR', 'RP', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 3);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tim Hill', 'NYY', 'RP', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 3);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Taijuan Walker', '(N/A)', 'SP', 'Claim', 'Riddle me This" (T)"', 1, NULL, 3);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Caleb Kilian', 'SF', 'RP', 'Claim', 'Philadelphia Paladins (T)', 11, NULL, 3);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Angel Martinez', 'CLE', '2B,OF', 'Claim', 'Philadelphia Paladins (T)', 6, NULL, 3);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Blaze Jordan', 'STL', '1B,3B', 'Drop', 'DirkDiggler (T)', NULL, NULL, 3);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Alan Roden', 'MIN', 'OF', 'Drop', 'Minneapolis Millers (T)', NULL, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Adrian Houser', 'SF', 'SP', 'Claim', 'Star Lord (T)', 1, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Michael Lorenzen', 'COL', 'SP', 'Claim', 'Star Lord (T)', 1, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ben Brown', 'CHC', 'SP', 'Claim', 'Star Lord (T)', 1, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Randy Vasquez', 'SD', 'SP', 'Claim', 'Star Lord (T)', 1, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tim Hill', 'NYY', 'RP', 'Claim', 'Riddle me This" (T)"', 1, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Griffin Canning', 'SD', 'SP', 'Claim', 'Star Lord (T)', 1, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nathan Church', 'STL', 'OF', 'Claim', 'Riddle me This" (T)"', 1, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Henry Davis', 'PIT', 'C', 'Claim', 'Star Lord (T)', 1, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler Wells', 'BAL', 'SP', 'Claim', 'Star Lord (T)', 2, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jace LaViolette', 'CLE', 'OF', 'Claim', 'XENOMORPH (T)', 0.25, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jake Meyers', 'HOU', 'OF', 'Claim', 'Master Chief (T)', 0, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Alek Thomas', 'ARI', 'OF', 'Claim', 'DirkDiggler (T)', 2, NULL, 2);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Curtis Mead', 'WSH', '1B,3B', 'Drop', 'DirkDiggler (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Mauricio Dubon', 'ATL', '2B,3B,SS,OF', 'Claim', 'DirkDiggler (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kody Clemens', 'MIN', '1B,2B,OF', 'Claim', 'Riddle me This" (T)"', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Steven Matz', 'TB', 'RP', 'Claim', 'Duke Nukem (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brayan Rocchio', 'CLE', '2B,SS', 'Claim', 'DirkDiggler (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Harrison Bader', 'SF', 'OF', 'Claim', 'Star Lord (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jake McCarthy', 'COL', 'OF', 'Claim', 'Crazyhorse (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Elian Pena', 'NYM', 'SS', 'Claim', 'XENOMORPH (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jose Ferrer', 'SEA', 'RP', 'Claim', 'DirkDiggler (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brandon Marsh', 'PHI', 'OF', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Rhys Hoskins', 'CLE', '1B', 'Claim', 'Riddle me This" (T)"', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Eric Lauer', 'TOR', 'SP', 'Claim', 'Riddle me This" (T)"', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Drey Jameson', 'ARI', 'RP', 'Drop', 'Crazyhorse (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Carmen Mlodzinski', 'PIT', 'RP', 'Claim', 'XENOMORPH (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Connor Norby', 'MIA', '1B,3B', 'Claim', 'Master Chief (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Shawn Armstrong', 'CLE', 'RP', 'Claim', 'Master Chief (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Vance Honeycutt', 'BAL', 'OF', 'Claim', 'XENOMORPH (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Abraham Toro', 'KC', '1B', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Keegan Akin', 'BAL', 'RP', 'Drop', 'XENOMORPH (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nasim Nunez', 'WSH', '2B,SS', 'Drop', 'XENOMORPH (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Graham Ashcraft', 'CIN', 'RP', 'Drop', 'XENOMORPH (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Ryan Ward', 'LAD', '1B,OF', 'Drop', 'XENOMORPH (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brandon Williamson', 'CIN', 'SP', 'Claim', 'Crazyhorse (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Walbert Urena', 'LAA', 'SP', 'Claim', 'XENOMORPH (T)', 0.25, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Zack Littell', 'WSH', 'SP', 'Claim', 'Master Chief (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Andrew Benintendi', 'CHW', 'OF', 'Claim', 'Master Chief (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jake Meyers', 'HOU', 'OF', 'Drop', 'Master Chief (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler Freeman', 'COL', 'OF', 'Claim', 'DirkDiggler (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Max Anderson', 'DET', '2B', 'Claim', 'Riddle me This" (T)"', 10, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nathan Lukes', 'TOR', 'OF', 'Claim', 'Crazyhorse (T)', 2, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Coleman Crow', 'MIL', 'SP', 'Lineup Change', 'Crazyhorse (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jared Koenig', 'MIL', 'RP', 'Claim', 'XENOMORPH (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Fernando Cruz', 'NYY', 'RP', 'Claim', 'Master Chief (T)', 0.25, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jake Meyers', 'HOU', 'OF', 'Claim', 'Master Chief (T)', 0.25, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Eduard Bazardo', 'SEA', 'RP', 'Claim', 'Star Lord (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Keegan Akin', 'BAL', 'RP', 'Claim', 'XENOMORPH (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Bryce Cunningham', 'NYY', 'SP', 'Drop', 'Master Chief (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler O''Neill', 'BAL', 'OF', 'Drop', 'XENOMORPH (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Craig Yoho', 'MIL', 'SP', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Bo Naylor', 'CLE', 'C', 'Claim', 'Riddle me This" (T)"', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Chase Hampton', 'NYY', 'SP', 'Claim', 'Riddle me This" (T)"', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jake Fraley', 'TB', 'OF', 'Claim', 'Crazyhorse (T)', 2, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Brandon Marsh', 'PHI', 'OF', 'Claim', 'Riddle me This" (T)"', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Eduardo Rodriguez', 'ARI', 'SP', 'Claim', 'Crazyhorse (T)', 2, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Andres Gimenez', 'TOR', '2B,SS', 'Claim', 'Minneapolis Millers (T)', 5, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Braylon Payne', 'MIL', 'OF', 'Drop', 'Minneapolis Millers (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Bryce Elder', 'ATL', 'SP', 'Claim', 'Crazyhorse (T)', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jeffrey Springs', 'ATH', 'SP', 'Claim', 'Minneapolis Millers (T)', 9, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Josh Hammond', 'KC', '3B,SS', 'Drop', 'Minneapolis Millers (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Trey Sweeney', 'DET', 'SS', 'Claim', 'Riddle me This" (T)"', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Liam Hendriks', '(N/A)', 'RP', 'Drop', 'Haru''s Throwing Stars (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Max Anderson', 'DET', '2B', 'Drop', 'Master Chief (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Mike Tauchman', 'NYM', 'OF', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Lane Thomas', 'KC', 'OF', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('John Schreiber', 'KC', 'RP', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Paul Sewald', 'ARI', 'RP', 'Claim', 'DirkDiggler (T)', 2, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Orion Kerkering', 'PHI', 'RP', 'Claim', 'DirkDiggler (T)', 3, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Roldy Brito', 'COL', '2B,OF', 'Claim', 'DirkDiggler (T)', 0, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Justin Sterner', 'ATH', 'RP', 'Claim', 'XENOMORPH (T)', 3, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler Holton', 'DET', 'RP', 'Claim', 'Minneapolis Millers (T)', 2, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Blaze Jordan', 'STL', '1B,3B', 'Claim', 'DirkDiggler (T)', 3, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Graham Ashcraft', 'CIN', 'RP', 'Claim', 'XENOMORPH (T)', 2, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Cole Sands', 'MIN', 'RP', 'Claim', 'Minneapolis Millers (T)', 2, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tyler O''Neill', 'BAL', 'OF', 'Claim', 'XENOMORPH (T)', 3, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Cedric Mullins', 'TB', 'OF', 'Claim', 'DirkDiggler (T)', 6, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jacob Morrison', 'MIL', 'SP', 'Claim', 'Riddle me This" (T)"', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kyle Leahy', 'STL', 'RP', 'Claim', 'Minneapolis Millers (T)', 6, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Kyle Karros', 'COL', '3B', 'Claim', 'XENOMORPH (T)', 2, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jeff McNeil', 'ATH', '2B,OF', 'Claim', 'Duke Nukem (T)', 5, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Mike Tauchman', 'NYM', 'OF', 'Claim', 'Riddle me This" (T)"', 1, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Alan Roden', 'MIN', 'OF', 'Claim', 'Minneapolis Millers (T)', 7, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Paul Goldschmidt', 'NYY', '1B', 'Claim', 'Duke Nukem (T)', 10, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Austin Wells', 'NYY', 'C', 'Claim', 'Iron Fisting (T)', 60, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Chase Shores', 'LAA', 'RP', 'Claim', 'Riddle me This" (T)"', 100, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Willi Castro', 'COL', '2B,3B,OF', 'Claim', 'Haru''s Throwing Stars (T)', 17, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Liam Hendriks', '(N/A)', 'RP', 'Lineup Change', 'Haru''s Throwing Stars (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Alex Vesia', 'LAD', 'RP', 'Claim', 'Minneapolis Millers (T)', 6, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jason Adam', 'SD', 'RP', 'Claim', 'Crazyhorse (T)', 2, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Mike Yastrzemski', 'ATL', 'OF', 'Claim', 'Master Chief (T)', 3, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Taylor Rogers', 'MIN', 'RP', 'Claim', 'Duke Nukem (T)', 5, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Michael Wacha', 'KC', 'SP', 'Claim', 'Iron Fisting (T)', 60, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Josh Jung', 'TEX', '3B', 'Claim', 'Riddle me This" (T)"', 76, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tony Santillan', 'CIN', 'RP', 'Claim', 'Duke Nukem (T)', 10, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Josh Bell', 'MIN', '1B', 'Claim', 'Haru''s Throwing Stars (T)', 23, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Triston McKenzie', 'SD', 'SP', 'Drop', 'Haru''s Throwing Stars (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nolan Arenado', 'ARI', '3B', 'Claim', 'Iron Fisting (T)', 60, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Andruw Monasterio', 'BOS', 'SS', 'Claim', 'Rick Grimes (T)', 10, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Simeon Woods-Richardson', 'MIN', 'SP', 'Claim', 'Haru''s Throwing Stars (T)', 17, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jarred Kelenic', 'CHW', 'OF', 'Drop', 'Haru''s Throwing Stars (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Grant Holmes', 'ATL', 'SP', 'Claim', 'Minneapolis Millers (T)', 51, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Juan Valera', 'BOS', 'SP', 'Drop', 'DirkDiggler (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Andres Chaparro', 'WSH', '1B', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Yohandy Morales', 'WSH', '1B,3B', 'Drop', 'Crazyhorse (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jose Corniell', 'TEX', 'RP', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Juaron Watts-Brown', 'BAL', 'SP', 'Drop', 'Master Chief (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Nick Burdi', '(N/A)', 'RP', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jurickson Profar', 'ATL', 'OF', 'Drop', 'Riddle me This" (T)"', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Jorge Soler', 'LAA', 'OF', 'Drop', 'XENOMORPH (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Bobby Witt Jr.', 'KC', 'SS', 'Drop', 'Duke Nukem (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Tarik Skubal', 'DET', 'SP', 'Drop', 'Star Lord (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Shohei Ohtani', 'LAD', 'UT,P', 'Drop', 'The Prime Evils (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Juan Soto', 'NYM', 'OF', 'Drop', 'Crazyhorse (T)', NULL, NULL, 1);
INSERT INTO fantrax."Fantrax_Transaction_History" VALUES ('Paul Skenes', 'PIT', 'SP', 'Drop', 'Iron Fisting (T)', NULL, NULL, 1);